### ISSUE TITLE
Sonido bajo en llamada

### ISSUE THREAD

**Issue by DanielSantamariaPixelsHub** [PixelsHub/manos-remotas-qa#11]
**Describe el error**
En llamada, con el volumen del movil a tope, suena bastante flojo.

**Reproducir**
Pasos para reproducir el comportamiento:
1. Establecer llamada.
2. Hablar.

**Comportamiento esperado**
Un volumen aceptable que haga sencilla la comunicación.

**Smartphone (complete la siguiente información):**
  - Dispositivo: Xiaomi Mi9 SE
  - SO: MIUI 12.0.1 (Android 10)

**Contexto adicional**
La otra parte de la llamada (Adri) reporta que me escucha aceptablemente

**Comment by Adrian-Pixels** [comment]
Dani no tenia puesta la cámara, algo que puede afectar el Web RTC por debajo.

**Comment by Adrian-Pixels** [comment]
Vale, ya se lo que he hecho. Tengo hecho que cuando se seleccione sin video pase a modo teléfono normal. ¿Lo cambios, que opinais?

**Comment by YisharPixelsHub** [comment]
Yo no entiendo a que te refieres con modo telefono normal

**Comment by Adrian-Pixels** [comment]
El tema de ponerte el teléfono en la oreja. Como sueles hablar por teléfono XD

**Comment by YisharPixelsHub** [comment]
Ah, pues no, creo que deberia estar siempre en modo manos libres, si lo puedes cambiar al vuelo hay que cambiarlo usando el sensor de proximidad, si no se puede pues siempre manos libres

**Comment by Adrian-Pixels** [comment]
Es lo que pensaba, quería solucionarlo y luego marcar otro issue con el tema del sensor

**Comment by Adrian-Pixels** [comment]
Subida una solución, queda probarla otra vez y confirmar para cerrar esto.
