### ISSUE TITLE
La aplicación no mantiene "activa" la pantalla y se bloquea el movil

### ISSUE THREAD

**Issue by DanielSantamariaPixelsHub** [PixelsHub/manos-remotas-qa#12]
**Describe el error**
Al utilizar la aplicación en periodos "largos", durante determinadas tareas, como una llamada, la aplicación no mantiene activa la pantalla, si no que entiende que esta inactiva, y según como este configurado cada dispositivo, apaga la pantalla y bloquea el movil, mientras la aplicación sigue funcionando. (Ej. estoy hablando un minuto por videollamada y si no toco la pantalla ésta se apaga y bloquea, lo q resulta muy molesto)

**Comportamiento esperado**
Durante tareas activas, como una videollamada, la aplicación debería mantener la pantalla activa, y asi evitar tener que tocar la pantalla cada 30 segundos para que no se apague.

**Smartphone (complete la siguiente información):**
  - Dispositivo: Xiaomi Mi 9 SE
  - SO: MIUI 12.0.1 (Android 10)

**Comment by Adrian-Pixels** [comment]
Ahora la aplicación mantiene la pantalla activa mientras haya una videollamada.
