### ISSUE TITLE
Explotó todo

### ISSUE THREAD

**Issue by AntonioParraPixelsHub** [PixelsHub/manos-remotas-qa#2]
**Describe el error**
Falló de la peor manera posible

**Reproducir**
Pasos para reproducir el comportamiento:
1. Descargue la app
2. La instalé
3. La abrí

**Comportamiento esperado**
Que funcionase. 

**Capturas de pantalla**
https://cflvdg.avoz.es/sc/gl3n_5Ugpgo3SWc8A-zgtg1XYls=/x/2018/10/13/00121539385133333795708/Foto/guetty.jpg

**Smartphone (complete la siguiente información):**
  - Dispositivo: Nokia 3310
  - SO:
 - Navegador IE 1.1
  - Versión 1.0

**Contexto adicional**
Agregue aquí cualquier otro contexto sobre el problema.

**Comment by Adrian-Pixels** [comment]
Pobre movil.... yo no he sido XD

**Comment by Adrian-Pixels** [comment]
Voy a cerrar esto para comenzar bien con las pruebas!
