### ISSUE TITLE
Chat incorrecto

### ISSUE THREAD

**Issue by pablogonzalez-pixelshub** [PixelsHub/manos-remotas-qa#21]
El chat aparece siempre coloreado y del lado derecho como si los mensajes fueran propios independientemente de quien los haya escrito.

**Comment by Adrian-Pixels** [comment]
Pues dame un poco mas de información porque yo creo que eso va desde el principio. De hecho lo creaste tu XD

**Comment by AntonioParraPixelsHub** [comment]
En el chat de la app (operator) todos los mensajes aparecen a la derecha. 
En mi movil, entro ahora como operator y toda la conversación aparece pegada a la derecha
