### ISSUE TITLE
Pregunta constante por acceso a última versión de RA en Google Play

### ISSUE THREAD

**Issue by pablogonzalez-pixelshub** [PixelsHub/manos-remotas-qa#22]
Al inicializar o entrar en un paso de procedimiento durante ejecución que tenga AR, Android pregunta constantemente al usuario por un pop-up que es necesaria la última versión de Servicios de Google Play para RA, independientemente de que luego el dispositivo no soporte AR. Imagino que esto será también un problema en las Vuzix si no se gestiona.

**Comment by AntonioParraPixelsHub** [comment]
Si, eso es un puto infierno si no tiene arcore

**Comment by Adrian-Pixels** [comment]
Solucionado, ahora solo lo pregunta una vez y si la #48 funciona solo lo preguntara una vez en toda la vida de la aplicación.
