### ISSUE TITLE
Se congela la imagen al enviar un archivo

### ISSUE THREAD

**Issue by AntonioParraPixelsHub** [PixelsHub/manos-remotas-qa#26]
Despues de enviar una foto y volver a la videollamada la imagen aparece congelada. La voz sigue funcionando
Da el error excepción 403

**Comment by Adrian-Pixels** [comment]
Que subiste de la galería o sacaste foto?

**Comment by AntonioParraPixelsHub** [comment]
La hice con la cámara. aparece el error excepcion 403

**Comment by Adrian-Pixels** [comment]
Decidimos bloquear el usar AR en procedimientos y enviar archivo desde la cámara cuando se esta en llamada para evitar este tipo de error.
