### ISSUE TITLE
Se envió la misma imagen tres veces. 

### ISSUE THREAD

**Issue by AntonioParraPixelsHub** [PixelsHub/manos-remotas-qa#27]
DEsde el movil, envié una imagan editada. Me salió el error 403 y la imagen apareció tres veces en el chat

**Comment by Adrian-Pixels** [comment]
Y solo le diste a subir una vez? desde el chat o desde archivos? se subió a la primera o intentaste varias veces subir imágenes?

**Comment by AntonioParraPixelsHub** [comment]
La subí una vez desde archivos. Solo lo intenté una vez
