### ISSUE TITLE
La pantalla de llamada entrante se queda al colgar en otro dispostivo

### ISSUE THREAD

**Issue by YisharPixelsHub** [PixelsHub/manos-remotas-qa#32]
**Describe el error**
Al hacer una llamada teniendo el mismo usuario logeado en la web y en android (o en dos webs), aparece correctamente la ventana de llamada entrante, pero no desaparece al coger la llamada en el otro dispositivo.

**Reproducir**
Pasos para reproducir el comportamiento:
1. Iniciar sesión en movil y web con el mismo usuario
2. Recibir una llamada
3. Coger la llamada en el movil
4. En la web no desaparece la llamada entrante

**Comportamiento esperado**
La ventana de llamada entrante deberia desaparecer como si se colgase

**Comment by YisharPixelsHub** [comment]
El problema es que no existe un mensaje de "llamada iniciada" que escuchar desde los dispositivos que no cogieron la llamada

**Comment by YisharPixelsHub** [comment]
Implementado en la web y en la app

**Comment by Adrian-Pixels** [comment]
Solucionado en Android, probado en el editor así que tiene que funcionar en build también.
