### ISSUE TITLE
Redondear el borde interno de los chats con foto

### ISSUE THREAD

**Issue by YisharPixelsHub** [PixelsHub/manos-remotas-qa#37]
En los chats con foto, la burbuja de chat tiene bordes redondeados, pero la imagen tiene bordes cuadrados. Convendría enmascararlo para que tenga el mismo radio en los bordes que la burbuja exterior

**Comment by Adrian-Pixels** [comment]
He hecho una primera aproximación falta ver si gusta y que cambio.

**Comment by Adrian-Pixels** [comment]
Lo cierro porque si no gusta o da error se crea otro se reabre.
