### ISSUE TITLE
El chat hace scroll solo

### ISSUE THREAD

**Issue by YisharPixelsHub** [PixelsHub/manos-remotas-qa#38]
**Describe el error**
El chat se mantiene haciendo scroll muy despacito despues de scrollearlo a mano.

**Reproducir**
Pasos para reproducir el comportamiento:
1. Vaya a un chat
2. Deslizar el dedo para hacer scroll
3. Soltar
4. El chat se sigue moviendo despacio durante mucho tiempo

**Comportamiento esperado**
El chat se para despues de un rato

**Smartphone (complete la siguiente información):**
  - Xiaomi Mi 9T

**Comment by Adrian-Pixels** [comment]
Lo marco como duplicate porque ya tengo uno con esto apuntado en otro lado.
