### ISSUE TITLE
Notificar al usuario cuando no se crea una operación al poner el nombre vacío.

### ISSUE THREAD

**Issue by Adrian-Pixels** [PixelsHub/manos-remotas-qa#4]
**Describe el error**
Notificar al usuario cuando no se crea una operación al poner el nombre vacío.

**Reproducir**
Pasos para reproducir el comportamiento:
1. Crear operación
2. No especificar nombre.
3. Darle a crear

**Comportamiento esperado**
Notificar al usuario que no se ha creado. Sin embargo simplemente sale a la pantalla anterior.

**Comment by Adrian-Pixels** [comment]
Esto ahora mismo no crea la operación, realmente solo cierra el panel y muestra la pantalla de selección de operaciones.

¿Qué os parece cambiar el botón de crear por una X de salir cuando el texto sea vacío?

**Comment by YisharPixelsHub** [comment]
Yo creo que deberias mostrar una alerta de "nombre no valido" o "introduzca el nombre", idealmente en vez de eso, volver a subir el scroll (si se deja de ver el input del nombre, que no estoy seguro) y marcarlo con un borde rojo o algo asi

**Comment by YisharPixelsHub** [comment]
De todas formas, si lo que dices es que una vez que le das no upedes cancelar, si, tambien hace falta un cancelar / cerrar

**Comment by Adrian-Pixels** [comment]
Si, tiene un cerrar con el atrás arriba a la izquierda. Tengo que ponerle un texto cerca el input con el error, además de agrandar el input en general porque hoy mismo le paso esto a dani.

**Comment by Adrian-Pixels** [comment]
Hecho, ya sale un mensaje de error.
