### ISSUE TITLE
Si se borra un archivo no se borra en el chat

### ISSUE THREAD

**Issue by AntonioParraPixelsHub** [PixelsHub/manos-remotas-qa#44]
**Describe el error**
Mando una foto desde la web, aparece en el chat. La borro y sigue en el chat...

Estaría bien que desapareciese del chat

**Comment by YisharPixelsHub** [comment]
Hay un problema de consistencia con esto y necesitamos decidir cómo proceder:

El chat funciona de forma que cada burbuja es individual y se muestra en base a la información que tiene del mensaje (si es un archivo, una llamada perdida, un mensaje de texto, etc). Para los archivos, la forma que tienen de saber si están "borrados" es pedir la foto al servidor, y si devuelve un 404 muestra el mensaje de "archivo borrado".

El problema es que el funcionamiento del motor de UI que usamos tiene caché, si ya se descargó una foto, no la vuelve a pedir al servidor (lo cual es bueno, por que si no se tardaría mucho en salir y volver a entrar del chat), con lo cual la "burbuja" del chat no puede saber que ese archivo ya no existe, hasta que se vuelve a recargar y vuelve a solicitar ese archivo.

Puedo hacer que se borre completamente esa burbuja al recibir el mensaje de archivo borrado, pero entonces tendriamos dos funcionamientos diferentes para el mismo caso: Al entrar en el chat, se muestra una burbuja que pone "archivo borrado", pero al borrarse algo mientras tenemos el chat abierto simplemente desaparece.

Tambien puedo hacer que desaparezcan las burbujas de archivos borrados al entrar al chat, pero me parece util ver que habia un archivo y se borró.

TL;DR:
- Podemos dejarlo como está, y que no se vea en el chat que se borró el archivo hasta que se recarge
- Podemos dejar los mensajes de "archivo borrado" en los que se cargan al abrir el chat, y hacer desaparecer los que se borran mientras está abierto (lo cual seria muy raro)
- Podemos omitir el mensaje de "archivo borrado", de forma que los chats con archivo desaparezcan cuando no lo consigan cargar (lo cual tambien quedaria raro, ver una animación de cargando y luego que desaparezca).

**Comment by YisharPixelsHub** [comment]
nvm, encontré una forma de hacerlo correctamente para que muestre archivo borrado igual que si fuese al abrir el chat, arreglado

**Comment by AntonioParraPixelsHub** [comment]
Perfecto! Esas cosas dan calidad al conjunto :)


Antonio J. Parra
PixelsHub

De: notifications@github.com
Enviado: 12 de octubre de 2020 16:57
Para: manos-remotas-qa@noreply.github.com
Responder a: reply@reply.github.com
Cc: antonioparra@pixels-hub.com; author@noreply.github.com
Asunto: Re: [PixelsHub/manos-remotas-qa] Si se borra un archivo no se borra en el chat (#44)


nvm, encontré una forma de hacerlo correctamente para que muestre archivo borrado igual que si fuese al abrir el chat, arreglado
