### ISSUE TITLE
Fallo al crear operación

### ISSUE THREAD

**Issue by YisharPixelsHub** [PixelsHub/manos-remotas-qa#45]
**Describe el error**
Al crear una operación saltó un error de excepción al añadir key 99 (ya existe) 

**Capturas de pantalla**
![Screenshot_2020-10-08-11-28-05-899_com.pixelshub.manosremotas.jpg](https://user-images.githubusercontent.com/65763477/95440938-d24e0580-0959-11eb-960f-5b5533083ff2.jpg)

**Smartphone (complete la siguiente información):**
  - Xiaomi Mi 9T

**Contexto adicional**
En la oficina hay microcortes, no me salto el fallo de conexión pero podría tener algo que ver. Ademas en el servidor no se han creado todos los tickets duplicados

**Comment by Adrian-Pixels** [comment]
Yo creo que ralamente es lo de los micro corté ya que eso se muestra cuando llega el mensaje de operación creada, por lo tanto ha entendido que le han llegado un montón de mensajes de operación creada.
