### ISSUE TITLE
La aplicación sigue vibrando en llamada en segundo plano

### ISSUE THREAD

**Issue by YisharPixelsHub** [PixelsHub/manos-remotas-qa#51]
**Describe el error**
Si la aplicación sigue recibiendo una llamada está vibrando aun en segundo plano y el usuario no sabe qué está pasando.
Propongo poner una notificación de "llamada entrante" para que lo sepa.

**Reproducir**
Pasos para reproducir el comportamiento:
1. Recibir una llamada
2. Sin contestar, poner la aplicación en segundo plano (volver al escritorio de android)
3. El movil sigue vibrando y no hay ningun indicador de por qué

**Comment by Adrian-Pixels** [comment]
Esto se debería solucionar con #32 pero queda apuntado también.

**Comment by Adrian-Pixels** [comment]
Escucha el evento OnFocusChange para desactivar la vibración, falta probarlo en build.
