### ISSUE TITLE
Excepcion. Secuence contains no matching elelment

### ISSUE THREAD

**Issue by AntonioParraPixelsHub** [PixelsHub/manos-remotas-qa#55]
Sale una ventana emergente con:
Secuence contains no matching elelment
Ejecutando la query: GET: operation/50/files

Simplemente abrí la app y le dí a una operación que teniamos abierta.
En la web estaba abierta como experto

Le dí a cerra a la ventana emergente y ahora no me entra en ninguna operación

**Comment by AntonioParraPixelsHub** [comment]
Me volvió a dar ese error con otra operacion: 
GET: operations/50/files

**Comment by Adrian-Pixels** [comment]
Creo que problema solucionado. Requiere pruebas con la nueva version.
