### ISSUE TITLE
Error de conexión demasiado sensible

### ISSUE THREAD

**Issue by AntonioParraPixelsHub** [PixelsHub/manos-remotas-qa#59]
Es demasiado sensible a los errores de conexión. 
¿No se puede hacer que tenga que tenga que estar más tiempo sin conexión antes de que salte?
He probado a poner el movil en modo avión con la app puesta y cuando vuelvo sigue funcionando. Quiero decir que a lo mejor no hace falta que salte tan pronto el aviso

**Comment by Adrian-Pixels** [comment]
Ya esta hecho, sin embargo te puede seguir saltando porque tengo que notificar que no estas conectado. Le he añadido un segundo mas de delay.

**Comment by AntonioParraPixelsHub** [comment]
Y....
¿No se podría avisar si intentas hacer algo que te avise...si estoy leyendo un documento que se bajó tampoco tiene porque decir nada.
Me imagino que en sitios sin wifi puede estar continuamente saltando la alerta.


Antonio J. Parra
PixelsHub

________________________________
  Mensaje original
________________________________
Mostrar detalles
De: notifications@github.com<mailto:notifications@github.com>
Enviado: 13 de octubre de 2020 15:53
Para: manos-remotas-qa@noreply.github.com<mailto:manos-remotas-qa@noreply.github.com>
Responder a: reply@reply.github.com<mailto:reply@reply.github.com>
Cc: antonioparra@pixels-hub.com<mailto:antonioparra@pixels-hub.com>; author@noreply.github.com<mailto:author@noreply.github.com>
Asunto: Re: [PixelsHub/manos-remotas-qa] Error de conexión demasiado sensible (#59)


Ya esta hecho, sin embargo te puede seguir saltando porque tengo que notificar que no estas conectado. Le he añadido un segundo mas de delay.

**Comment by Adrian-Pixels** [comment]
Imagínate que te llega una llamada, se desconecta y espero dos segundos en indicarlo, sin embargo tu le das a aceptar. Y claro, no hace nada. Es algo que me acaba de pasar y no había contemplado.

De hecho el sistema de conexiones y reconexiones debería ser mucho mas potente pero hay que diseñarlo para la próxima versión.

**Comment by AntonioParraPixelsHub** [comment]
Es un poco parecido al móvil, cuando pierdes cobertura no sabes cuando la otra persona dejó de escucharte. Es que me salta continuamente en la oficina. Si, ya sé que no es una red solida como para manejar en remoto un reactor nuclear, pero para esto...

**Comment by Adrian-Pixels** [comment]
He creado una manera mucho menos intrusiva de mostrar que no hay internte. Te sale un icono arriba a la izquierda. Asi no molesta pero te sigue indicando bien cuando no estes conectado.
