### ISSUE TITLE
Burbujas de chat enviado duplicadas

### ISSUE THREAD

**Issue by YisharPixelsHub** [PixelsHub/manos-remotas-qa#60]
**Describe el error**
Al enviar un chat, aparece dos veces, siendo una de las instancias fantasma (es decir, no lo envia dos veces al servidor, solo ocurre en el cliente)

**Reproducir**
No tengo claro cual es el repro, pero me ha pasado varias veces. Es probable que tenga que ver con bloquear el telefono y/o perder y recuperar la conexión al socket (huele a doble suscripción a algún evento)

**Capturas de pantalla**
![imgpsh_mobile_save](https://user-images.githubusercontent.com/65763477/95867204-2ea19280-0d69-11eb-9fcc-738b5a907605.jpg)

**Comment by Adrian-Pixels** [comment]
Creo que es el al intentar reconectar tantas veces llega un punto que hay dos web sockets a la vez. Debería ser facil de solucionar pero no tanto de probar.

**Comment by Adrian-Pixels** [comment]
No doy replicado el error para comprobarlo.
