### ISSUE TITLE
Apareció cuatro veces el mensaje en el chat.

### ISSUE THREAD

**Issue by AntonioParraPixelsHub** [PixelsHub/manos-remotas-qa#61]
Ver imagen. 
solo lo escribí una vez. 
En la web solo apareció una vez.
Al volver a entrar solo aparece una vez.
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/66787162/95947649-62bf9680-0def-11eb-9fda-cbc105e8f667.png)

**Comment by Adrian-Pixels** [comment]
Asi con captura mola mucho, lo marco como duplicado al ser el mismo issue #60 que indico @YisharPixelsHub ayer.
