### ISSUE TITLE
Al "minimizar" la llamada y volver fallan los pings y la imagen propia

### ISSUE THREAD

**Issue by AntonioParraPixelsHub** [PixelsHub/manos-remotas-qa#65]
¡Mola mucho lo de minimizar la llamada y que se quede como una ventana flotante!

Cuando vuelves a la llamada:
1. Dejan de funcionar lo pings desde el pc al móvil
2. Se deja de ver la imagen propia

![image](https://user-images.githubusercontent.com/66787162/95968517-d1135180-0e0d-11eb-804e-3df7e8a1c95d.png)

**Comment by YisharPixelsHub** [comment]
Arreglado el ping, pero no consigo reproducir que pierdas tu propio video, ¿seguro que habias llamado o contestado con video?
