### ISSUE TITLE
Recordar usuario en el login de la web (y contraseña?)

### ISSUE THREAD

**Issue by YisharPixelsHub** [PixelsHub/manos-remotas-qa#7]

**Comment by Adrian-Pixels** [comment]
Esto ya te lo debería hacer el navegador si le dejas no?

**Comment by YisharPixelsHub** [comment]
No, porque no estoy usando un form, lo estoy haciendo en javascript y Chrome no sabe que es un login

**Comment by Adrian-Pixels** [comment]
Pues es curioso porque a Antonio le dejo guardar la contraseña en el navegador pero a mi me salta un error cada vez.

**Comment by YisharPixelsHub** [comment]
Funciona solo
