### ISSUE TITLE
No se recive una"llamada sin respuesta" si cuelga el usuario remoto

### ISSUE THREAD

**Issue by Adrian-Pixels** [PixelsHub/manos-remotas-qa#70]
**Reproducir**
Pasos para reproducir el comportamiento:
1. Llamar desde un usuario
2. El otro cuelga
3. No se muestra en el chat

**Comportamiento esperado**
Un mensaje por lo menos que no cuesta na.

**Comment by YisharPixelsHub** [comment]
Arreglado en el backend, pero ahora el comportamiento no es correcto en la app:
- No se registran los mensajes de llamada sin respuesta (en la web si)
- Si se llama desde la app y se rechaza en la web, funciona correctamente. Sin embargo al llamar desde la web y rechazar en la app, se registra dos veces (estás mandando eventos que no deberías?)

**Comment by YisharPixelsHub** [comment]
Aprovecho para plantear: ¿deberiamos usar un mensaje diferente para las llamadas "perdidas" y "rechazadas"? En el backend es cambiar una tonteria, y creo que es un feedback mas claro para el usuario

**Comment by Adrian-Pixels** [comment]
Ponerlo en la aplicación también es una tontería así que si quieres, ponlo.
